export const blogPosts = [
  {
    id: 1,
    title: "How AI Voice Agents Are Replacing Traditional Call Centers",
    title_ar: "كيف تستبدل وكلاء الصوت بالذكاء الاصطناعي مراكز الاتصال التقليدية",
    slug: "ai-voice-agents-replacing-call-centers",
    image: "/blog/ai_voice.png",
    category: "AI & Automation",
    category_ar: "الذكاء الاصطناعي والأتمتة",
    author: "Adonix Team",
    author_ar: "فريق أدونيكس",
    date: "July 2026",
    date_ar: "يوليو 2026",
    readTime: "6 min read",
    readTime_ar: "6 دقائق قراءة",
    excerpt: "Call centers have long been the most expensive, hardest-to-scale part of customer operations. AI voice agents are changing that math entirely — here's how.",
    excerpt_ar: "طالما كانت مراكز الاتصال هي الجزء الأكثر تكلفة والأصعب في التوسع. وكلاء الذكاء الاصطناعي يغيرون هذه المعادلة تماماً — إليك كيف.",
    content: `For decades, the call center was treated as a necessary cost center. Businesses accepted long hold times because there was no real alternative. That's no longer true. AI voice agents can now hold natural conversations.`,
    content_ar: `لعقود، كان يُعامل مركز الاتصال كمركز تكلفة ضروري. قبلت الشركات فترات الانتظار الطويلة لعدم وجود بديل حقيقي. هذا لم يعد صحيحاً. يمكن لوكلاء الذكاء الاصطناعي الآن إجراء محادثات طبيعية.`
  },
  {
    id: 2,
    title: "5 Signs Your Business Needs Workflow Automation",
    title_ar: "5 علامات تدل على أن عملك يحتاج إلى أتمتة سير العمل",
    slug: "signs-your-business-needs-workflow-automation",
    image: "/blog/workflow.png",
    category: "Marketing",
    category_ar: "التسويق",
    author: "Adonix Team",
    author_ar: "فريق أدونيكس",
    date: "July 2026",
    date_ar: "يوليو 2026",
    readTime: "5 min read",
    readTime_ar: "5 دقائق قراءة",
    excerpt: "Most businesses don't realize how much time and money manual processes are quietly costing them — until they see it laid out. Here are five clear signs it's time to automate.",
    excerpt_ar: "معظم الشركات لا تدرك مقدار الوقت والمال الذي تكلفه العمليات اليدوية بصمت — إليك خمس علامات واضحة تدل على أن الوقت قد حان للأتمتة.",
    content: `Workflow automation used to be something only large enterprises could afford. Today, it's one of the highest-leverage investments any growing business can make.`,
    content_ar: `في الماضي، كانت أتمتة سير العمل شيئاً لا تتحمله سوى الشركات الكبيرة. اليوم، هي واحدة من أهم الاستثمارات التي يمكن لأي عمل متنامٍ القيام بها.`
  },
  {
    id: 3,
    title: "Inside the Adonix Method: Diagnose, Deploy, Dominate",
    title_ar: "داخل طريقة أدونيكس: التشخيص، النشر، السيطرة",
    slug: "inside-the-adonix-method",
    image: "/blog/method.png",
    category: "Company News",
    category_ar: "أخبار الشركة",
    author: "Adonix Team",
    author_ar: "فريق أدونيكس",
    date: "July 2026",
    date_ar: "يوليو 2026",
    readTime: "4 min read",
    readTime_ar: "4 دقائق قراءة",
    featured: true,
    excerpt: "Every system we build at Adonix follows the same three-phase framework. Here's a closer look at how it works — and why it produces results that generic software doesn't.",
    excerpt_ar: "كل نظام نبنيه في أدونيكس يتبع نفس الإطار المكون من ثلاث مراحل. إليك نظرة فاحصة على كيفية عمله.",
    content: `When businesses come to us, they often already know something is inefficient. That's why every engagement at Adonix follows the same disciplined framework: Diagnose, Deploy, Dominate.`,
    content_ar: `عندما تأتي الشركات إلينا، غالباً ما يعرفون أن هناك شيئاً غير فعال. لهذا السبب، يتبع كل مشروع في أدونيكس نفس الإطار المنضبط: التشخيص، النشر، والسيطرة.`
  },
  {
    id: 4,
    title: "B2B vs B2C Lead Generation: Why One Strategy Doesn't Fit Both",
    title_ar: "توليد العملاء B2B مقابل B2C: لماذا استراتيجية واحدة لا تناسب الاثنين",
    slug: "b2b-vs-b2c-lead-generation",
    image: "/blog/b2b.png",
    category: "Marketing",
    category_ar: "التسويق",
    author: "Adonix Team",
    author_ar: "فريق أدونيكس",
    date: "July 2026",
    date_ar: "يوليو 2026",
    readTime: "7 min read",
    readTime_ar: "7 دقائق قراءة",
    excerpt: "The tools might be similar, but the intent couldn't be more different. Here's why treating B2B leads like B2C buyers is costing you enterprise clients.",
    excerpt_ar: "قد تكون الأدوات متشابهة، لكن النية مختلفة تماماً. إليك سبب كون التعامل مع عملاء B2B مثل B2C يكلفك خسارة عملاء الشركات.",
    content: `A common mistake agencies make is applying B2C urgency to B2B sales cycles. B2B requires nurturing, authority, and multi-stakeholder approval.`,
    content_ar: `من الأخطاء الشائعة التي ترتكبها الوكالات تطبيق إلحاح B2C على مبيعات B2B. تتطلب B2B الرعاية والسلطة وموافقة أصحاب المصلحة المتعددين.`
  },
  {
    id: 5,
    title: "Why Your Client Portal Might Be Costing You Clients",
    title_ar: "لماذا قد تكلفك بوابة العملاء خسارة العملاء",
    slug: "client-portal-costing-you-clients",
    image: "/blog/portal.png",
    category: "Product Updates",
    category_ar: "تحديثات المنتج",
    author: "Adonix Team",
    author_ar: "فريق أدونيكس",
    date: "July 2026",
    date_ar: "يوليو 2026",
    readTime: "5 min read",
    readTime_ar: "5 دقائق قراءة",
    excerpt: "A client portal is supposed to add value. But if it's clunky, hard to use, or disconnected from the rest of your process, it's doing the exact opposite.",
    excerpt_ar: "من المفترض أن تضيف بوابة العملاء قيمة. ولكن إذا كانت معقدة أو صعبة الاستخدام، فهي تفعل العكس تماماً.",
    content: `Client portals should be seamless extensions of your service. If clients have to remember a separate password just to check a status update, you are creating friction.`,
    content_ar: `يجب أن تكون بوابات العملاء امتداداً سلساً لخدمتك. إذا اضطر العملاء إلى تذكر كلمة مرور منفصلة فقط للتحقق من تحديث الحالة، فأنت تخلق عقبات.`
  }
];
